let foodDatabase = [
    {
        id: 1,
        name: "pizza",
        cuisine: "Italian",
        origin: "Italy",
        vegetarian: false,
        price: 18.99,
        description: 'Wood-fired perfection with San Marzano tomatoes, fresh mozzarella, and fragrant basil.',
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&h=420&fit=crop'
    },
    {
        id: 2,
        name: "burger",
        cuisine: "American",
        origin: "USA",
        vegetarian: false,
        price: 15.99,
        description: 'Prime Angus beef with aged cheddar, caramelized onions, and our signature sauce.',
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=420&fit=crop'
    },
    {
        id: 3,
        name: "pasta",
        cuisine: "Italian",
        origin: "Italy",
        vegetarian: true,
        price: 16.99,
        description: 'Al dente spaghetti tossed in a rich, slow-simmered pomodoro with garden herbs.',
        image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=420&fit=crop'
    },
    {
        id: 4,
        name: "sushi",
        cuisine: "Japanese",
        origin: "Japan",
        vegetarian: false,
        price: 22.99,
        description: 'Premium nori rolls with seasoned rice, fresh salmon, and creamy avocado.',
        image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=600&h=420&fit=crop'
    },
    {
        id: 5,
        name: "tacos",
        cuisine: "Mexican",
        origin: "Mexico",
        vegetarian: false,
        price: 14.99,
        description: 'Soft corn tortillas with grilled carne asada, pico de gallo, and lime crema.',
        image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=420&fit=crop'
    },
    {
        id: 6,
        name: "pad thai",
        cuisine: "Thai",
        origin: "Thailand",
        vegetarian: true,
        price: 17.99,
        description: 'Stir-fried rice noodles with shrimp, bean sprouts, tamarind sauce, and crushed peanuts.',
        image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&h=420&fit=crop'
    },
    {
        id: 7,
        name: "ramen",
        cuisine: "Japanese",
        origin: "Japan",
        vegetarian: false,
        price: 18.99,
        description: 'Rich tonkotsu broth with chashu pork, soft egg, nori, and hand-pulled noodles.',
        image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=420&fit=crop'
    },
    {
        id: 8,
        name: "steak",
        cuisine: "American",
        origin: "USA",
        vegetarian: false,
        price: 38.99,
        description: '30-day dry-aged prime ribeye, chargrilled to perfection with rosemary butter.',
        image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&h=420&fit=crop'
    }
]

const heroBackground = [
  'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1920&q=80',
  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1920&q=80',
  'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=1920&q=80',
  'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=1920&q=80',
  'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=1920&q=80'
];

const fallbackGradients = {
    Italian:  'linear-gradient(135deg, #f7971e, #ffd200)',
    American: 'linear-gradient(135deg, #e43a15, #e65245)',
    Japanese: 'linear-gradient(135deg, #1a1a2e, #c31432)',
    Mexican:  'linear-gradient(135deg, #11998e, #38ef7d)',
    Thai:     'linear-gradient(135deg, #f2709c, #ff9472)'
};

const maidoInfo = {
  chef: 'Mitsuharu Tsumura',
  cuisine: 'Nikkei — Japanese-Peruvian Fusion',
  address: 'Calle San Martín 399, Miraflores, Lima, Perú',
  phone: '+51 (01) 313-5100',
  hours: 'Mon–Sat 1:00 PM – 10:00 PM',
  sunday: 'Closed',
  philosophy: `Life is movement. Nothing is static or absolute. Like family trees, cuisines are constantly being redefined, their identities enriched by an intense intercultural exchange which has formed the basis of all civilization.`
};

const translations = {
  en: {
    navMenu:'Menu', navAbout:'About', navRes:'Reservations', navContact:'Contact',
    heroSince:'Est. 2026', heroTitle:'Our Menu', heroDesc:'Curated flavors from the Gen D Kitchen', heroBtn:'Explore Dishes',
    sectionSub:'Handpicked Selection', sectionTitle:"Today's Offerings",
    filterAll:'All', Italian:'Italian', American:'American', Japanese:'Japanese', Mexican:'Mexican', Thai:'Thai',
    resSub:'Book Your Experience', resTitle:'Reserve & Pre-Order',
    formName:'Name', formEmail:'Email', formPhone:'Phone', formGuests:'Guests', formDate:'Date', formTime:'Time',
    placeName:'Your name', placeEmail:'your@email.com', placePhone:'08X-XXX-XXXX',
    preOrderTitle:'Pre-Order Food', preOrderTotal:'Total:',
    submitBtn:'Confirm Reservation',
    infoTitle:'Why Reserve in Advance?',
    infoDesc:'Skip the wait and secure your table at Gen D. Pre-order your favorite dishes so they\'re ready the moment you arrive.',
    infoSeating:'Priority seating upon arrival', infoPreOrder:'Your pre-orders prepared fresh on time', infoOccasion:'Special occasion? Let us know!',
    confirmTitle:'Reservation Confirmed!', confirmP1:"We've received your booking and pre-order.", confirmP2:'A confirmation will be sent to your email.', confirmBtn:'Done', confirmRef:'Ref:',
    aboutTitle:'Our Story', aboutSub:'Inspired by Maido, Lima',
    aboutP1:'Welcome to Gen D — where the spirit of Maido, ranked among the world\'s finest restaurants, inspires every plate.',
    aboutP2:'Life is movement. Nothing is static or absolute. Like family trees, cuisines are constantly being redefined, their identities enriched by an intense intercultural exchange which has formed the basis of all civilization.',
    aboutP3:'Our cuisine is Nikkei — a harmony of Japanese precision and Peruvian soul. Led by Chef Mitsuharu Tsumura, we honor this tradition of intercultural exchange, blending the freshest local ingredients with techniques passed across oceans and generations.',
    aboutP4:'Every dish at Gen D tells a story of movement — of flavors, people, and cultures colliding to create something entirely new.',
    aboutChef:'Mitsuharu Tsumura', aboutChefTitle:'Executive Chef • Maido, Lima',
    contactTitle:'Get in Touch', contactSub:'Visit or reach out', contactVisit:'Visit Us',
    contactAddress:'Calle San Martín 399, Miraflores, Lima, Perú', contactPhone:'+51 (01) 313-5100', contactHours:'Mon–Sat 1:00 PM – 10:00 PM', contactSunday:'Closed',
    contactAddrLabel:'Address', contactPhoneLabel:'Phone', contactHoursLabel:'Hours', contactSundayLabel:'Sunday',
    footerText:'Fine dining crafted with passion.',
    veg:'Vegetarian', nonVeg:'Non-Veg',
    guest:'Guest', guests:'Guests'
  },
  es: {
    navMenu:'Menú', navAbout:'Nosotros', navRes:'Reservas', navContact:'Contacto',
    heroSince:'Est. 2026', heroTitle:'Nuestro Menú', heroDesc:'Sabores seleccionados de la cocina Gen D', heroBtn:'Explorar Platos',
    sectionSub:'Selección Seleccionada', sectionTitle:'Ofertas de Hoy',
    filterAll:'Todo', Italian:'Italiano', American:'Americano', Japanese:'Japonés', Mexican:'Mexicano', Thai:'Tailandés',
    resSub:'Reserve su Experiencia', resTitle:'Reserve y Pre-Ordene',
    formName:'Nombre', formEmail:'Correo', formPhone:'Teléfono', formGuests:'Invitados', formDate:'Fecha', formTime:'Hora',
    placeName:'Su nombre', placeEmail:'su@email.com', placePhone:'08X-XXX-XXXX',
    preOrderTitle:'Pre-Ordene Comida', preOrderTotal:'Total:',
    submitBtn:'Confirmar Reserva',
    infoTitle:'¿Por Qué Reservar con Antelación?',
    infoDesc:'Evite la espera y reserve su mesa en Gen D. Pre-ordene sus platos favoritos para que estén listos cuando llegue.',
    infoSeating:'Asiento prioritario al llegar', infoPreOrder:'Sus pre-órdenes preparadas frescas a tiempo', infoOccasion:'¿Ocasión especial? ¡Díganos!',
    confirmTitle:'¡Reserva Confirmada!', confirmP1:'Hemos recibido su reserva y pre-orden.', confirmP2:'Se enviará una confirmación a su correo.', confirmBtn:'Listo', confirmRef:'Ref:',
    aboutTitle:'Nuestra Historia', aboutSub:'Inspirado en Maido, Lima',
    aboutP1:'Bienvenido a Gen D — donde el espíritu de Maido, clasificado entre los mejores restaurantes del mundo, inspira cada plato.',
    aboutP2:'La vida es movimiento. Nada es estático ni absoluto. Como los árboles genealógicos, las cocinas se redefinen constantemente, sus identidades enriquecidas por un intenso intercambio intercultural.',
    aboutP3:'Nuestra cocina es Nikkei — una armonía de precisión japonesa y alma peruana. Liderados por el Chef Mitsuharu Tsumura, honramos esta tradición de intercambio cultural.',
    aboutP4:'Cada plato en Gen D cuenta una historia de movimiento — de sabores, personas y culturas que chocan para crear algo completamente nuevo.',
    aboutChef:'Mitsuharu Tsumura', aboutChefTitle:'Chef Ejecutivo • Maido, Lima',
    contactTitle:'Contáctenos', contactSub:'Visite o comuníquese', contactVisit:'Visítenos',
    contactAddress:'Calle San Martín 399, Miraflores, Lima, Perú', contactPhone:'+51 (01) 313-5100', contactHours:'Lun–Sáb 1:00 PM – 10:00 PM', contactSunday:'Cerrado',
    contactAddrLabel:'Dirección', contactPhoneLabel:'Teléfono', contactHoursLabel:'Horario', contactSundayLabel:'Domingo',
    footerText:'Comida fina hecha con pasión.',
    veg:'Vegetariano', nonVeg:'No Vegetariano',
    guest:'Invitado', guests:'Invitados'
  },
  fr: {
    navMenu:'Menu', navAbout:'À Propos', navRes:'Réservations', navContact:'Contact',
    heroSince:'Établi 2026', heroTitle:'Notre Menu', heroDesc:'Saveurs sélectionnées de la cuisine Gen D', heroBtn:'Découvrir les Plats',
    sectionSub:'Sélection Choisie', sectionTitle:'Offres du Jour',
    filterAll:'Tout', Italian:'Italien', American:'Américain', Japanese:'Japonais', Mexican:'Mexicain', Thai:'Thaïlandais',
    resSub:'Réservez Votre Expérience', resTitle:'Réservez & Pré-Commandez',
    formName:'Nom', formEmail:'Email', formPhone:'Téléphone', formGuests:'Invités', formDate:'Date', formTime:'Heure',
    placeName:'Votre nom', placeEmail:'votre@email.com', placePhone:'08X-XXX-XXXX',
    preOrderTitle:'Pré-Commandez', preOrderTotal:'Total:',
    submitBtn:'Confirmer la Réservation',
    infoTitle:'Pourquoi Réserver à l\'Avance ?',
    infoDesc:'Sautez l\'attente et réservez votre table chez Gen D. Pré-commandez vos plats favoris.',
    infoSeating:'Place prioritaire à l\'arrivée', infoPreOrder:'Vos pré-commandes préparées fraîches', infoOccasion:'Occasion spéciale ? Dites-nous !',
    confirmTitle:'Réservation Confirmée !', confirmP1:'Nous avons reçu votre réservation.', confirmP2:'Une confirmation sera envoyée à votre email.', confirmBtn:'Terminé', confirmRef:'Réf:',
    aboutTitle:'Notre Histoire', aboutSub:'Inspiré par Maido, Lima',
    aboutP1:'Bienvenue chez Gen D — où l\'esprit de Maido, classé parmi les meilleurs restaurants du monde, inspire chaque assiette.',
    aboutP2:'La vie est mouvement. Rien n\'est statique ou absolu. Comme les arbres généalogiques, les cuisines sont constamment redéfinies.',
    aboutP3:'Notre cuisine est Nikkei — une harmonie de précision japonaise et d\'âme péruvienne. Menés par le Chef Mitsuharu Tsumura.',
    aboutP4:'Chaque plat chez Gen D raconte une histoire de mouvement — de saveurs, de personnes et de cultures.',
    aboutChef:'Mitsuharu Tsumura', aboutChefTitle:'Chef Exécutif • Maido, Lima',
    contactTitle:'Contactez-Nous', contactSub:'Visitez ou contactez', contactVisit:'Visitez-Nous',
    contactAddress:'Calle San Martín 399, Miraflores, Lima, Pérou', contactPhone:'+51 (01) 313-5100', contactHours:'Lun–Sam 1:00 PM – 10:00 PM', contactSunday:'Fermé',
    contactAddrLabel:'Adresse', contactPhoneLabel:'Téléphone', contactHoursLabel:'Horaires', contactSundayLabel:'Dimanche',
    footerText:'Cuisine raffinée faite avec passion.',
    veg:'Végétarien', nonVeg:'Non Végétarien',
    guest:'Invité', guests:'Invités'
  },
  ja: {
    navMenu:'メニュー', navAbout:'私たちについて', navRes:'予約', navContact:'お問い合わせ',
    heroSince:'2026年設立', heroTitle:'メニュー', heroDesc:'Gen Dキッチンが選ぶ厳選フレーバー', heroBtn:'料理を見る',
    sectionSub:'厳選セレクション', sectionTitle:'本日のおすすめ',
    filterAll:'すべて', Italian:'イタリアン', American:'アメリカン', Japanese:'日本料理', Mexican:'メキシカン', Thai:'タイ料理',
    resSub:'体験を予約', resTitle:'予約＆事前注文',
    formName:'お名前', formEmail:'メール', formPhone:'電話番号', formGuests:'人数', formDate:'日付', formTime:'時間',
    placeName:'お名前', placeEmail:'your@email.com', placePhone:'08X-XXX-XXXX',
    preOrderTitle:'事前注文', preOrderTotal:'合計:',
    submitBtn:'予約を確定',
    infoTitle:'事前予約のメリット',
    infoDesc:'待ち時間をスキップしてGen Dのテーブルを確保。お気に入りの料理を事前注文。',
    infoSeating:'到着時の優先席', infoPreOrder:'事前注文は到着時に準備', infoOccasion:'特別な機会？お知らせください！',
    confirmTitle:'予約確定！', confirmP1:'予約と事前注文を受け付けました。', confirmP2:'確認メールが送信されます。', confirmBtn:'完了', confirmRef:'参照:',
    aboutTitle:'私たちの物語', aboutSub:'リマのマイドに触発されて',
    aboutP1:'Gen Dへようこそ — 世界最高峰のレストラン、マイドの精神がすべての皿にインスピレーションを与えています。',
    aboutP2:'人生は動きです。静的なものも絶対的なものもありません。料理は常に再定義され、そのアイデンティティは異文化間の交流によって豊かになります。',
    aboutP3:'私たちの料理はニッケイ — 日本の精度とペルーの魂の調和です。三ッ橋光治シェフのもと、この伝統を尊重します。',
    aboutP4:'Gen Dのすべての料理は動きの物語を語ります — 味、人、文化が衝突し、まったく新しいものを創造します。',
    aboutChef:'三ッ橋 光治', aboutChefTitle:'エグゼクティブシェフ • マイド、リマ',
    contactTitle:'お問い合わせ', contactSub:'ご来店またはお問い合わせ', contactVisit:'ご来店',
    contactAddress:'Calle San Martín 399, Miraflores, Lima, ペルー', contactPhone:'+51 (01) 313-5100', contactHours:'月–土 1:00 PM – 10:00 PM', contactSunday:'定休日',
    contactAddrLabel:'住所', contactPhoneLabel:'電話', contactHoursLabel:'営業時間', contactSundayLabel:'日曜日',
    footerText:'情熱を込めたファインダイニング。',
    veg:'ベジタリアン', nonVeg:'非ベジタリアン',
    guest:'名様', guests:'名様'
  },
  zh: {
    navMenu:'菜单', navAbout:'关于我们', navRes:'预订', navContact:'联系我们',
    heroSince:'成立于2026年', heroTitle:'我们的菜单', heroDesc:'Gen D厨房精心挑选的风味', heroBtn:'探索菜肴',
    sectionSub:'精心挑选', sectionTitle:'今日供应',
    filterAll:'全部', Italian:'意大利', American:'美式', Japanese:'日式', Mexican:'墨西哥', Thai:'泰式',
    resSub:'预订您的体验', resTitle:'预订和预购',
    formName:'姓名', formEmail:'邮箱', formPhone:'电话', formGuests:'人数', formDate:'日期', formTime:'时间',
    placeName:'您的姓名', placeEmail:'your@email.com', placePhone:'08X-XXX-XXXX',
    preOrderTitle:'预购食物', preOrderTotal:'总计:',
    submitBtn:'确认预订',
    infoTitle:'为什么要提前预订？',
    infoDesc:'跳过等待，在Gen D预订您的餐桌。提前订购您最喜爱的菜肴。',
    infoSeating:'到达时优先入座', infoPreOrder:'您的预购准时新鲜准备', infoOccasion:'特殊场合？告诉我们！',
    confirmTitle:'预订已确认！', confirmP1:'我们已收到您的预订和预购。', confirmP2:'确认邮件将发送到您的邮箱。', confirmBtn:'完成', confirmRef:'编号:',
    aboutTitle:'我们的故事', aboutSub:'灵感来自利马的Maido',
    aboutP1:'欢迎来到Gen D — 这里融合了世界顶级餐厅Maido的精神，激发每一道菜肴。',
    aboutP2:'生命在于运动。没有任何事物是静止或绝对的。像家谱一样，烹饪文化不断被重新定义。',
    aboutP3:'我们的料理是日式秘鲁融合菜 — 日本精准与秘鲁灵魂的和谐。在三ッ橋光治主厨的带领下。',
    aboutP4:'Gen D的每道菜都讲述着一个运动的故事 — 风味、人和文化的碰撞，创造出全新的东西。',
    aboutChef:'三ッ橋光治', aboutChefTitle:'行政主厨 • Maido，利马',
    contactTitle:'联系我们', contactSub:'来访或联系', contactVisit:'访问我们',
    contactAddress:'Calle San Martín 399, Miraflores, Lima, 秘鲁', contactPhone:'+51 (01) 313-5100', contactHours:'周一至周六 1:00 PM – 10:00 PM', contactSunday:'休息',
    contactAddrLabel:'地址', contactPhoneLabel:'电话', contactHoursLabel:'营业时间', contactSundayLabel:'周日',
    footerText:'充满激情的精致餐饮。',
    veg:'素食', nonVeg:'非素食',
    guest:'位客人', guests:'位客人'
  },
  pt: {
    navMenu:'Cardápio', navAbout:'Sobre', navRes:'Reservas', navContact:'Contato',
    heroSince:'Est. 2026', heroTitle:'Nosso Cardápio', heroDesc:'Sabores selecionados da cozinha Gen D', heroBtn:'Explorar Pratos',
    sectionSub:'Seleção Especial', sectionTitle:'Ofertas de Hoje',
    filterAll:'Todos', Italian:'Italiano', American:'Americano', Japanese:'Japonês', Mexican:'Mexicano', Thai:'Tailandês',
    resSub:'Reserve Sua Experiência', resTitle:'Reserve e Pré-Peça',
    formName:'Nome', formEmail:'Email', formPhone:'Telefone', formGuests:'Convidados', formDate:'Data', formTime:'Hora',
    placeName:'Seu nome', placeEmail:'seu@email.com', placePhone:'08X-XXX-XXXX',
    preOrderTitle:'Pré-Peça Comida', preOrderTotal:'Total:',
    submitBtn:'Confirmar Reserva',
    infoTitle:'Por Que Reservar com Antecedência?',
    infoDesc:'Evite a espera e reserve sua mesa no Gen D. Pré-peça seus pratos favoritos.',
    infoSeating:'Assento prioritário na chegada', infoPreOrder:'Seus pré-pedidos preparados na hora', infoOccasion:'Ocasião especial? Nos avise!',
    confirmTitle:'Reserva Confirmada!', confirmP1:'Recebemos sua reserva e pré-pedido.', confirmP2:'Uma confirmação será enviada ao seu email.', confirmBtn:'Concluído', confirmRef:'Ref:',
    aboutTitle:'Nossa História', aboutSub:'Inspirado no Maido, Lima',
    aboutP1:'Bem-vindo ao Gen D — onde o espírito do Maido, classificado entre os melhores restaurantes do mundo, inspira cada prato.',
    aboutP2:'A vida é movimento. Nada é estático ou absoluto. As culinárias estão constantemente sendo redefinidas.',
    aboutP3:'Nossa cozinha é Nikkei — uma harmonia de precisão japonesa e alma peruana. Liderados pelo Chef Mitsuharu Tsumura.',
    aboutP4:'Cada prato no Gen D conta uma história de movimento — de sabores, pessoas e culturas.',
    aboutChef:'Mitsuharu Tsumura', aboutChefTitle:'Chef Executivo • Maido, Lima',
    contactTitle:'Fale Conosco', contactSub:'Visite ou entre em contato', contactVisit:'Visite-nos',
    contactAddress:'Calle San Martín 399, Miraflores, Lima, Peru', contactPhone:'+51 (01) 313-5100', contactHours:'Seg–Sáb 1:00 PM – 10:00 PM', contactSunday:'Fechado',
    contactAddrLabel:'Endereço', contactPhoneLabel:'Telefone', contactHoursLabel:'Horário', contactSundayLabel:'Domingo',
    footerText:'Alta gastronomia feita com paixão.',
    veg:'Vegetariano', nonVeg:'Não Vegetariano',
    guest:'Convidado', guests:'Convidados'
  },
  de: {
    navMenu:'Speisekarte', navAbout:'Über Uns', navRes:'Reservierungen', navContact:'Kontakt',
    heroSince:'Gegr. 2026', heroTitle:'Unsere Speisekarte', heroDesc:'Ausgewählte Aromen aus der Gen D Küche', heroBtn:'Gerichte Entdecken',
    sectionSub:'Handverlesene Auswahl', sectionTitle:'Angebote von Heute',
    filterAll:'Alle', Italian:'Italienisch', American:'Amerikanisch', Japanese:'Japanisch', Mexican:'Mexikanisch', Thai:'Thailändisch',
    resSub:'Buchen Sie Ihr Erlebnis', resTitle:'Reservieren & Vorbestellen',
    formName:'Name', formEmail:'E-Mail', formPhone:'Telefon', formGuests:'Gäste', formDate:'Datum', formTime:'Uhrzeit',
    placeName:'Ihr Name', placeEmail:'ihre@email.com', placePhone:'08X-XXX-XXXX',
    preOrderTitle:'Essen Vorbestellen', preOrderTotal:'Gesamt:',
    submitBtn:'Reservierung Bestätigen',
    infoTitle:'Warum im Voraus Reservieren?',
    infoDesc:'Überspringen Sie das Warten und sichern Sie sich Ihren Tisch bei Gen D. Bestellen Sie Ihre Lieblingsgerichte vor.',
    infoSeating:'Prioritäre Sitzplatzvergabe', infoPreOrder:'Ihre Vorbestellungen frisch zubereitet', infoOccasion:'Besonderer Anlass? Teilen Sie uns mit!',
    confirmTitle:'Reservierung Bestätigt!', confirmP1:'Wir haben Ihre Buchung und Vorbestellung erhalten.', confirmP2:'Eine Bestätigung wird an Ihre E-Mail gesendet.', confirmBtn:'Fertig', confirmRef:'Ref:',
    aboutTitle:'Unsere Geschichte', aboutSub:'Inspiriert von Maido, Lima',
    aboutP1:'Willkommen bei Gen D — wo der Geist von Maido, einem der besten Restaurants der Welt, jeden Teller inspiriert.',
    aboutP2:'Leben ist Bewegung. Nichts ist statisch oder absolut. Küchen werden ständig neu definiert.',
    aboutP3:'Unsere Küche ist Nikkei — eine Harmonie japanischer Präzision und peruanischer Seele. Unter der Leitung von Chefkoch Mitsuharu Tsumura.',
    aboutP4:'Jedes Gericht bei Gen D erzählt eine Geschichte von Bewegung — von Aromen, Menschen und Kulturen.',
    aboutChef:'Mitsuharu Tsumura', aboutChefTitle:'Executive Chef • Maido, Lima',
    contactTitle:'Kontaktieren Sie Uns', contactSub:'Besuchen oder kontaktieren Sie uns', contactVisit:'Besuchen Sie Uns',
    contactAddress:'Calle San Martín 399, Miraflores, Lima, Peru', contactPhone:'+51 (01) 313-5100', contactHours:'Mo–Sa 1:00 PM – 10:00 PM', contactSunday:'Geschlossen',
    contactAddrLabel:'Adresse', contactPhoneLabel:'Telefon', contactHoursLabel:'Öffnungszeiten', contactSundayLabel:'Sonntag',
    footerText:'Feine Küche mit Leidenschaft zubereitet.',
    veg:'Vegetarisch', nonVeg:'Nicht Vegetarisch',
    guest:'Gast', guests:'Gäste'
  },
  ko: {
    navMenu:'메뉴', navAbout:'소개', navRes:'예약', navContact:'연락처',
    heroSince:'2026년 설립', heroTitle:'메뉴', heroDesc:'Gen D 키친의 엄선된 맛', heroBtn:'요리 탐험',
    sectionSub:'엄선된 셀렉션', sectionTitle:'오늘의 메뉴',
    filterAll:'전체', Italian:'이탈리안', American:'아메리칸', Japanese:'일본식', Mexican:'멕시칸', Thai:'타이',
    resSub:'경험 예약하기', resTitle:'예약 및 사전 주문',
    formName:'이름', formEmail:'이메일', formPhone:'전화번호', formGuests:'인원', formDate:'날짜', formTime:'시간',
    placeName:'이름', placeEmail:'your@email.com', placePhone:'08X-XXX-XXXX',
    preOrderTitle:'음식 사전 주문', preOrderTotal:'합계:',
    submitBtn:'예약 확인',
    infoTitle:'사전 예약의 이점',
    infoDesc:'대기 시간을 건너뛰고 Gen D에서 테이블을 확보하세요. 좋아하는 요리를 미리 주문하세요.',
    infoSeating:'도착 시 우선 좌석 배정', infoPreOrder:'사전 주문은 도착 시 신선하게 준비', infoOccasion:'특별한 행사? 알려주세요!',
    confirmTitle:'예약 확인됨!', confirmP1:'예약 및 사전 주문이 접수되었습니다.', confirmP2:'확인 이메일이 발송됩니다.', confirmBtn:'완료', confirmRef:'참조:',
    aboutTitle:'우리의 이야기', aboutSub:'리마의 Maido에서 영감을 받아',
    aboutP1:'Gen D에 오신 것을 환영합니다 — 세계 최고의 레스토랑 중 하나인 Maido의 정신이 모든 접시에 영감을 줍니다.',
    aboutP2:'인생은 움직임입니다. 정적인 것도 절대적인 것도 없습니다. 요리는 끊임없이 재정의됩니다.',
    aboutP3:'저희 요리는 Nikkei — 일본의 정밀함과 페루의 영혼의 조화입니다. Mitsuharu Tsumura 셰프가 이끕니다.',
    aboutP4:'Gen D의 모든 요리는 움직임의 이야기를 들려줍니다 — 맛, 사람, 문화가 충돌하여 완전히 새로운 것을 창조합니다.',
    aboutChef:'Mitsuharu Tsumura', aboutChefTitle:'총괄 셰프 • Maido, 리마',
    contactTitle:'문의하기', contactSub:'방문 또는 문의', contactVisit:'방문하기',
    contactAddress:'Calle San Martín 399, Miraflores, Lima, 페루', contactPhone:'+51 (01) 313-5100', contactHours:'월–토 1:00 PM – 10:00 PM', contactSunday:'휴무',
    contactAddrLabel:'주소', contactPhoneLabel:'전화', contactHoursLabel:'영업 시간', contactSundayLabel:'일요일',
    footerText:'열정으로 만든 파인 다이닝.',
    veg:'채식', nonVeg:'비채식',
    guest:'명', guests:'명'
  },
  ar: {
    navMenu:'القائمة', navAbout:'عنا', navRes:'الحجوزات', navContact:'اتصل بنا',
    heroSince:'تأسست 2026', heroTitle:'قائمتنا', heroDesc:'نكهات مختارة من مطبخ Gen D', heroBtn:'استكشف الأطباق',
    sectionSub:'اختيار انتقائي', sectionTitle:'عروض اليوم',
    filterAll:'الكل', Italian:'إيطالي', American:'أمريكي', Japanese:'ياباني', Mexican:'مكسيكي', Thai:'تايلاندي',
    resSub:'احجز تجربتك', resTitle:'احجز واطلب مسبقاً',
    formName:'الاسم', formEmail:'البريد', formPhone:'الهاتف', formGuests:'الضيوف', formDate:'التاريخ', formTime:'الوقت',
    placeName:'اسمك', placeEmail:'بريدك@email.com', placePhone:'08X-XXX-XXXX',
    preOrderTitle:'اطلب طعاماً مسبقاً', preOrderTotal:'المجموع:',
    submitBtn:'تأكيد الحجز',
    infoTitle:'لماذا الحجز مسبقاً؟',
    infoDesc:'تجاوز الانتظار واحجز طاولتك في Gen D. اطلب أطباقك المفضلة مسبقاً.',
    infoSeating:'مقعد ذو أولوية عند الوصول', infoPreOrder:'طلباتك المسبقة تُحضر طازجة في الوقت المحدد', infoOccasion:'مناسبة خاصة؟ أخبرنا!',
    confirmTitle:'تم تأكيد الحجز!', confirmP1:'لقد تلقينا حجزك وطلبك المسبق.', confirmP2:'سيتم إرسال تأكيد إلى بريدك الإلكتروني.', confirmBtn:'تم', confirmRef:'المرجع:',
    aboutTitle:'قصتنا', aboutSub:'مستوحى من Maido، ليما',
    aboutP1:'مرحباً بكم في Gen D — حيث روح Maido، المصنف من بين أفضل مطاعم العالم، يلهم كل طبق.',
    aboutP2:'الحياة حركة. لا شيء ثابت أو مطلق. المطابخ تعاد تعريفها باستمرار، هوياتها تثريها التبادل الثقافي المكثف.',
    aboutP3:'مطبخنا هو Nikkei — انسجام بين الدقة اليابانية والروح البيروفية. بقيادة الشيف Mitsuharu Tsumura.',
    aboutP4:'كل طبق في Gen D يروي قصة حركة — نكهات وأشخاص وثقافات تتصادم لتخلق شيئاً جديداً تماماً.',
    aboutChef:'Mitsuharu Tsumura', aboutChefTitle:'الشيف التنفيذي • Maido، ليما',
    contactTitle:'اتصل بنا', contactSub:'زرنا أو اتصل بنا', contactVisit:'زرنا',
    contactAddress:'Calle San Martín 399, Miraflores, Lima, بيرو', contactPhone:'+51 (01) 313-5100', contactHours:'الإثنين–السبت 1:00 م – 10:00 م', contactSunday:'مغلق',
    contactAddrLabel:'العنوان', contactPhoneLabel:'الهاتف', contactHoursLabel:'ساعات العمل', contactSundayLabel:'الأحد',
    footerText:'تناول طعام راقٍ بشغف.',
    veg:'نباتي', nonVeg:'غير نباتي',
    guest:'ضيف', guests:'ضيوف'
  },
  ru: {
    navMenu:'Меню', navAbout:'О нас', navRes:'Бронирование', navContact:'Контакты',
    heroSince:'Основан 2026', heroTitle:'Наше Меню', heroDesc:'Избранные вкусы от кухни Gen D', heroBtn:'Изучить Блюда',
    sectionSub:'Избранная Подборка', sectionTitle:'Предложения Дня',
    filterAll:'Все', Italian:'Итальянская', American:'Американская', Japanese:'Японская', Mexican:'Мексиканская', Thai:'Тайская',
    resSub:'Забронируйте Впечатление', resTitle:'Бронирование и Предзаказ',
    formName:'Имя', formEmail:'Email', formPhone:'Телефон', formGuests:'Гости', formDate:'Дата', formTime:'Время',
    placeName:'Ваше имя', placeEmail:'your@email.com', placePhone:'08X-XXX-XXXX',
    preOrderTitle:'Предзаказ Еды', preOrderTotal:'Итого:',
    submitBtn:'Подтвердить Бронирование',
    infoTitle:'Почему Стоит Бронировать Заранее?',
    infoDesc:'Пропустите ожидание и забронируйте столик в Gen D. Предзакажите любимые блюда.',
    infoSeating:'Приоритетное размещение по прибытии', infoPreOrder:'Ваши предзаказы приготовлены свежими вовремя', infoOccasion:'Особый случай? Сообщите нам!',
    confirmTitle:'Бронирование Подтверждено!', confirmP1:'Мы получили ваше бронирование и предзаказ.', confirmP2:'Подтверждение будет отправлено на ваш email.', confirmBtn:'Готово', confirmRef:'Реф:',
    aboutTitle:'Наша История', aboutSub:'Вдохновлено Maido, Лима',
    aboutP1:'Добро пожаловать в Gen D — где дух Maido, одного из лучших ресторанов мира, вдохновляет каждое блюдо.',
    aboutP2:'Жизнь — это движение. Ничто не статично и не абсолютно. Кулинарные традиции постоянно переосмысливаются.',
    aboutP3:'Наша кухня — Nikkei — гармония японской точности и перуанской души. Под руководством шеф-повара Mitsuharu Tsumura.',
    aboutP4:'Каждое блюдо в Gen D рассказывает историю движения — вкусов, людей и культур.',
    aboutChef:'Mitsuharu Tsumura', aboutChefTitle:'Шеф-повар • Maido, Лима',
    contactTitle:'Свяжитесь с Нами', contactSub:'Посетите или свяжитесь', contactVisit:'Посетите Нас',
    contactAddress:'Calle San Martín 399, Miraflores, Lima, Перу', contactPhone:'+51 (01) 313-5100', contactHours:'Пн–Сб 1:00 PM – 10:00 PM', contactSunday:'Закрыто',
    contactAddrLabel:'Адрес', contactPhoneLabel:'Телефон', contactHoursLabel:'Часы работы', contactSundayLabel:'Воскресенье',
    footerText:'Изысканная кухня, приготовленная со страстью.',
    veg:'Вегетарианский', nonVeg:'Невегетарианский',
    guest:'Гость', guests:'Гостей'
  },
  th: {
    navMenu:'เมนู', navAbout:'เกี่ยวกับเรา', navRes:'การจอง', navContact:'ติดต่อ',
    heroSince:'เปิดตัว 2026', heroTitle:'เมนูของเรา', heroDesc:'รสชาติที่คัดสรรจากครัว Gen D', heroBtn:'สำรวจเมนู',
    sectionSub:'คัดสรรพิเศษ', sectionTitle:'เมนูวันนี้',
    filterAll:'ทั้งหมด', Italian:'อิตาเลียน', American:'อเมริกัน', Japanese:'ญี่ปุ่น', Mexican:'เม็กซิกัน', Thai:'ไทย',
    resSub:'จองประสบการณ์ของคุณ', resTitle:'จองและสั่งจองล่วงหน้า',
    formName:'ชื่อ', formEmail:'อีเมล', formPhone:'โทรศัพท์', formGuests:'จำนวนแขก', formDate:'วันที่', formTime:'เวลา',
    placeName:'ชื่อของคุณ', placeEmail:'your@email.com', placePhone:'08X-XXX-XXXX',
    preOrderTitle:'สั่งอาหารล่วงหน้า', preOrderTotal:'รวม:',
    submitBtn:'ยืนยันการจอง',
    infoTitle:'ทำไมต้องจองล่วงหน้า?',
    infoDesc:'ข้ามคิวและจองโต๊ะที่ Gen D สั่งอาหารจานโปรดล่วงหน้าเพื่อให้พร้อมเมื่อคุณมาถึง',
    infoSeating:'ที่นั่งพิเศษเมื่อมาถึง', infoPreOrder:'อาหารที่สั่งล่วงหน้าปรุงสดใหม่ทันเวลา', infoOccasion:'โอกาสพิเศษ? แจ้งให้เราทราบ!',
    confirmTitle:'การจองได้รับการยืนยัน!', confirmP1:'เราได้รับการจองและการสั่งอาหารล่วงหน้าของคุณแล้ว', confirmP2:'อีเมลยืนยันจะถูกส่งไปยังคุณ', confirmBtn:'เสร็จสิ้น', confirmRef:'อ้างอิง:',
    aboutTitle:'เรื่องราวของเรา', aboutSub:'ได้รับแรงบันดาลใจจาก Maido, ลิมา',
    aboutP1:'ยินดีต้อนรับสู่ Gen D — ที่ซึ่งจิตวิญญาณของ Maido ร้านอาหารระดับโลก สร้างแรงบันดาลใจให้ทุกจาน',
    aboutP2:'ชีวิตคือการเคลื่อนไหว ไม่มีอะไรหยุดนิ่งหรือแน่นอน อาหารแต่ละประเภทถูกนิยามใหม่เสมอ ผ่านการแลกเปลี่ยนทางวัฒนธรรม',
    aboutP3:'อาหารของเราคือนิคเคอิ — ความกลมกลืนระหว่างความแม่นยำแบบญี่ปุ่นและจิตวิญญาณแบบเปรู นำโดยเชฟ Mitsuharu Tsumura',
    aboutP4:'ทุกจานที่ Gen D เล่าเรื่องราวของการเคลื่อนไหว — ของรสชาติ ผู้คน และวัฒนธรรมที่มาบรรจบกัน',
    aboutChef:'Mitsuharu Tsumura', aboutChefTitle:'เชฟบริหาร • Maido, ลิมา',
    contactTitle:'ติดต่อเรา', contactSub:'เยี่ยมชมหรือติดต่อ', contactVisit:'เยี่ยมชมเรา',
    contactAddress:'Calle San Martín 399, Miraflores, Lima, เปรู', contactPhone:'+51 (01) 313-5100', contactHours:'จ–ส 13:00 – 22:00 น.', contactSunday:'หยุด',
    contactAddrLabel:'ที่อยู่', contactPhoneLabel:'โทรศัพท์', contactHoursLabel:'เวลาเปิดทำการ', contactSundayLabel:'วันอาทิตย์',
    footerText:'อาหารชั้นเลิศที่ปรุงด้วยความหลงใหล',
    veg:'มังสวิรัติ', nonVeg:'ไม่มังสวิรัติ',
    guest:'ท่าน', guests:'ท่าน'
  }
};

const langList = ['en', 'es', 'fr', 'ja', 'zh', 'pt', 'de', 'ko', 'ar', 'ru', 'th'];