let foodDatabase = [
    {
        id: 1,
        name: "pizza",
        cuisine: "Italian",
        origin: "Italy",
        price: 12.99,
        size: ["small", "medium", "large"],
        vegetarian: false,
    },
    {
        id: 2,
        name: "burger",
        cuisine: "American",
        origin: "USA",
        price: 10.99,
        size: ["small", "medium", "large"],
        vegetarian: false,
    },
    {
        id: 3,
        name: "pasta",
        cuisine: "Italian",
        origin: "Italy",
        price: 11.99,
        size: ["small", "medium", "large"],
        vegetarian: true,
    },
    {
        id: 4,
        name: "sushi",
        cuisine: "Japanese",
        origin: "Japan",
        price: 14.99,
        size: ["small", "medium", "large"],
        vegetarian: false,
    },
    {
        id: 5,
        name: "tacos",
        cuisine: "Mexican",
        origin: "Mexico",
        price: 9.99,
        size: ["small", "medium", "large"],
        vegetarian: false,
    },
    {
        id: 6,
        name: "pad thai",
        cuisine: "Thai",
        origin: "Thailand",
        price: 13.99,
        size: ["small", "medium", "large"],
        vegetarian: true,
    },
    {
        id: 7,
        name: "ramen",
        cuisine: "Japanese",
        origin: "Japan",
        price: 12.99,
        size: ["small", "medium", "large"],
        vegetarian: false,
    },
    {
        id: 8,
        name: "steak",
        cuisine: "American",
        origin: "USA",
        price: 19.99,
        size: ["small", "medium", "large"],
        vegetarian: false,
    }
]